// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProzorro.Data;

#nullable disable

namespace WebProzorro.Migrations
{
    [DbContext(typeof(WebProzorroContext))]
    [Migration("20220717190238_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Prozorro.Models.CategoryDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcuringEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("ProcuringEntityId");

                    b.ToTable("CategoryDTOs", (string)null);
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Сriterion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileDTOId");

                    b.ToTable("Сriterion");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.BaseAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseAddress");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAddress");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VendorDTOId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Classification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.ContactPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPoint");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePublished")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VendorDTOId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Identifier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDTOId");

                    b.ToTable("Identifier");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDTOId");

                    b.HasIndex("ProductDTOId");

                    b.HasIndex("ProfileDTOId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.MinOrderValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MinOrderValue");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.ProcuringEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ContactPointId")
                        .HasColumnType("int");

                    b.Property<string>("IdentifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactPointId");

                    b.HasIndex("IdentifierId");

                    b.ToTable("ProcuringEntity");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Requirement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequirementGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequirementGroupId");

                    b.HasIndex("UnitId");

                    b.ToTable("Requirement");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.RequirementGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("СriterionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("СriterionId");

                    b.ToTable("RequirementGroup");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.RequirementResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ProductDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductDTOId");

                    b.ToTable("RequirementResponse");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ContactPointId")
                        .HasColumnType("int");

                    b.Property<string>("IdentifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Scale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactPointId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("OfferDTOId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValueAddetTaxIncluded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Value");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ContactPointId")
                        .HasColumnType("int");

                    b.Property<string>("IdentifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactPointId");

                    b.HasIndex("IdentifierId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Prozorro.Models.OfferDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinOrderValueId")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MinOrderValueId");

                    b.HasIndex("ValueId");

                    b.ToTable("OfferDTOs", (string)null);
                });

            modelBuilder.Entity("Prozorro.Models.ProductDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ClassificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("IdentifierId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDTOs", (string)null);
                });

            modelBuilder.Entity("Prozorro.Models.ProfileDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("ValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ValueId");

                    b.ToTable("ProfileDTOs", (string)null);
                });

            modelBuilder.Entity("Prozorro.Models.VendorDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorDTOs", (string)null);
                });

            modelBuilder.Entity("Prozorro.Models.Internals.DeliveryAddress", b =>
                {
                    b.HasBaseType("Prozorro.Models.Internals.BaseAddress");

                    b.Property<string>("OfferDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("OfferDTOId");

                    b.HasDiscriminator().HasValue("DeliveryAddress");
                });

            modelBuilder.Entity("Prozorro.Models.CategoryDTO", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.Classification", "Classification")
                        .WithMany("CategoryDTOs")
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Prozorro.Models.Internals.ProcuringEntity", "ProcuringEntity")
                        .WithMany()
                        .HasForeignKey("ProcuringEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("ProcuringEntity");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Сriterion", b =>
                {
                    b.HasOne("Prozorro.Models.ProfileDTO", null)
                        .WithMany("Criteria")
                        .HasForeignKey("ProfileDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Category", b =>
                {
                    b.HasOne("Prozorro.Models.VendorDTO", null)
                        .WithMany("Categories")
                        .HasForeignKey("VendorDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Document", b =>
                {
                    b.HasOne("Prozorro.Models.VendorDTO", null)
                        .WithMany("Documents")
                        .HasForeignKey("VendorDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Identifier", b =>
                {
                    b.HasOne("Prozorro.Models.ProductDTO", null)
                        .WithMany("AlternativeIdentifiers")
                        .HasForeignKey("ProductDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Image", b =>
                {
                    b.HasOne("Prozorro.Models.CategoryDTO", null)
                        .WithMany("Images")
                        .HasForeignKey("CategoryDTOId");

                    b.HasOne("Prozorro.Models.ProductDTO", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductDTOId");

                    b.HasOne("Prozorro.Models.ProfileDTO", null)
                        .WithMany("Images")
                        .HasForeignKey("ProfileDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.ProcuringEntity", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.DeliveryAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.ContactPoint", "ContactPoint")
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId");

                    b.Navigation("Address");

                    b.Navigation("ContactPoint");

                    b.Navigation("Identifier");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Requirement", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.RequirementGroup", null)
                        .WithMany("Requirements")
                        .HasForeignKey("RequirementGroupId");

                    b.HasOne("Prozorro.Models.Internals.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.RequirementGroup", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.Сriterion", null)
                        .WithMany("RequirementGroups")
                        .HasForeignKey("СriterionId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.RequirementResponse", b =>
                {
                    b.HasOne("Prozorro.Models.ProductDTO", null)
                        .WithMany("RequirementResponses")
                        .HasForeignKey("ProductDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Supplier", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.DeliveryAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.ContactPoint", "ContactPoint")
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.Identifier", "Identifier")
                        .WithMany("Suppliers")
                        .HasForeignKey("IdentifierId");

                    b.HasOne("Prozorro.Models.OfferDTO", null)
                        .WithMany("Suppliers")
                        .HasForeignKey("OfferDTOId");

                    b.Navigation("Address");

                    b.Navigation("ContactPoint");

                    b.Navigation("Identifier");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Vendor", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.BaseAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.ContactPoint", "ContactPoint")
                        .WithMany()
                        .HasForeignKey("ContactPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ContactPoint");

                    b.Navigation("Identifier");
                });

            modelBuilder.Entity("Prozorro.Models.OfferDTO", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.MinOrderValue", "MinOrderValue")
                        .WithMany()
                        .HasForeignKey("MinOrderValueId");

                    b.HasOne("Prozorro.Models.Internals.Value", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinOrderValue");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Prozorro.Models.ProductDTO", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.Classification", "Classification")
                        .WithMany("ProductDTOs")
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Prozorro.Models.Internals.Identifier", "Identifier")
                        .WithMany()
                        .HasForeignKey("IdentifierId");

                    b.HasOne("Prozorro.Models.Internals.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Classification");

                    b.Navigation("Identifier");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Prozorro.Models.ProfileDTO", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.Classification", "Classification")
                        .WithMany("ProfileDTOs")
                        .HasForeignKey("ClassificationId");

                    b.HasOne("Prozorro.Models.Internals.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prozorro.Models.Internals.Value", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("Unit");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Prozorro.Models.VendorDTO", b =>
                {
                    b.HasOne("Prozorro.Models.Internals.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.DeliveryAddress", b =>
                {
                    b.HasOne("Prozorro.Models.OfferDTO", null)
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("OfferDTOId");
                });

            modelBuilder.Entity("Prozorro.Models.CategoryDTO", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Сriterion", b =>
                {
                    b.Navigation("RequirementGroups");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Classification", b =>
                {
                    b.Navigation("CategoryDTOs");

                    b.Navigation("ProductDTOs");

                    b.Navigation("ProfileDTOs");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.Identifier", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Prozorro.Models.Internals.RequirementGroup", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Prozorro.Models.OfferDTO", b =>
                {
                    b.Navigation("DeliveryAddresses");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Prozorro.Models.ProductDTO", b =>
                {
                    b.Navigation("AlternativeIdentifiers");

                    b.Navigation("Images");

                    b.Navigation("RequirementResponses");
                });

            modelBuilder.Entity("Prozorro.Models.ProfileDTO", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Prozorro.Models.VendorDTO", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
